#!/usr/bin/env bash
uuid=""
devices_file="devices"

if [ ! -f "$devices_file" ]; then
    touch "$devices_file"
fi

 while IFS= read -r device || [ -n "$device" ]; do
    device="${device%$'\r'}"

    if dev_path=$(blkid -U "$device" 2>/dev/null); then
        uuid="$device"
    fi
done < "$devices_file"

if [ -z "$uuid" ]; then
    i=0
    devices=()
    
    while read -r name type size removable; do
        if [ "$removable" = "1" ] && [ "$type" = "part" ]; then
            echo "$i) $name | $size" 
            devices[$i]="$name"
            i=$((i + 1))
        fi
    done < <(lsblk -rpn -o NAME,TYPE,SIZE,RM)

    read -r -p "No device found.  Please select a device: " choice 
    device="${devices[$choice]}"

    uuid=$(lsblk -no UUID "$device")
    echo "$uuid" >> "$devices_file"
fi

if ! findmnt -rn -S "UUID=$uuid" >/dev/null; then
    echo Mounting Device...
    sudo mount UUID="$uuid" /mnt/"$uuid"/
    echo Mounted
fi

if [ ! -d "/mnt/$uuid" ]; then 
    echo creating directory...
    sudo mkdir "/mnt/$uuid"
fi


echo "Installing packagages"
python -m pip install -r reqs &> /dev/null
python app.py